
name: Conda aarch64 Test

on:
  # Triggers the workflow on push or pull request events but only for the "stable" branch
  push:
    paths:
      - 'requirements.txt'
      - 'cog.yml'
      - 'vqgan.yml'
      - 'predict.py'
      - 'generate.py'
      - '.github/workflows/conda-test.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
          
jobs:
  test:
    strategy:
      matrix:
        python: ['3.9', '3.10']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        activate-conda: true
        python-version: ${{ matrix.python }}
        conda-channels: anaconda, conda-forge
    - name: Install pytorch
      run: conda install -c kumatea pytorch numpy cpuonly
    - name: Create conda environment
      run: conda create --name vqgarm python=${{ matrix.python }}
    - name: Activate conda 
      run: conda activate vqgarm
